a=input("Enter int value\n")
print(type(a))
b=int(a)
print(type(b))
c=input("Enter float value\n")
print(type(c))
d=float(c)
print(type(d))
e=input("Enter complex value\n")
print(type(e))
f=complex(e)
print(type(f))
g=input("Enter bool value\n")
print(type(g))
h=bool(g)
print(type(h))
print(a)
print(c)
print(e)
print(g)